steps:
  # 1. Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_ID}/${_REPO_NAME}:${SHORT_SHA}"
      - "."

  # 2. Push the image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_ID}/${_REPO_NAME}:${SHORT_SHA}"

  # 3. Get the application's environment variables from Secret Manager
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - "gcloud secrets versions access latest --secret=${_ENV_SECRET_NAME} > /workspace/env_vars"

  # 4. Deploy to GCE using a secure environment file
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud compute scp /workspace/env_vars ${_GCE_USER}@${_GCE_INSTANCE_NAME}:$/tmp/siburger-bot.env --zone ${_GCE_ZONE}

        gcloud compute ssh ${_GCE_USER}@${_GCE_INSTANCE_NAME} --zone ${_GCE_ZONE} --command=" \
          if [ \\\$(sudo docker ps -q -f name=^\siburger-bot\$) ]; then \
            echo 'Stopping and removing old container...' && \
            sudo docker stop siburger-bot && sudo docker rm siburger-bot; \
          fi && \
          \
          echo 'Pulling new image...' && \
          sudo docker pull \"${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_ID}/${_REPO_NAME}:${SHORT_SHA}\" && \
          \
          echo 'Starting new container with environment file...' && \
          sudo docker run -d --name siburger-bot --restart=always \
            --env-file \"/tmp/siburger-bot.env\" \
            \"${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_ID}/${_REPO_NAME}:${SHORT_SHA}\" && \
          \
          echo 'Deployment Succeeded. Cleaning up environment file...' && \
          rm \"/tmp/siburger-bot.env\" && \
          \
          echo 'Cleanup Succeeded.' \
        "

substitutions:
  _REGION: "us-central1"
  _REGISTRY_ID: "my-applications"
  _GCE_INSTANCE_NAME: "instance-1"
  _GCE_ZONE: "asia-southeast2-a"
  _GCE_USER: "gcloud_user"
  _ENV_SECRET_NAME: "siburger-bot-env"
  _REPO_NAME: "siburger-bot"

options:
  logging: CLOUD_LOGGING_ONLY
